/*
 * VEDIC KUNDLI ENGINE
 * --------------------
 * Uses Swiss Ephemeris for astronomical planetary positions.
 * Uses Swiss Ephemeris Lahiri sidereal mode directly.
 * Ephemeris files are fetched at runtime from the official
 * Astrodienst Swiss Ephemeris repository. No astronomical
 * position is approximated or generated by this UI layer.
 */

(function (window) {
    "use strict";

    /* Build marker: confirms the browser loaded this exact engine file. */
    window.KUNDLI_ENGINE_BUILD = "3.0.0-swiss-ephemeris";

    console.log(
        "[Kundli Engine] Build 3.0.0-swiss-ephemeris loaded."
    );


    /* =========================================================
       SWISS EPHEMERIS RUNTIME
       ---------------------------------------------------------
       Browser build uses the official Swiss Ephemeris engine
       through the @swisseph/browser WebAssembly package.
       Planetary ephemeris files are fetched directly from the
       official Astrodienst-maintained Swiss Ephemeris repository.
    ========================================================= */

    const SWISS_JS_URL =
        "https://esm.sh/@swisseph/browser@1.3.1?bundle";

    const OFFICIAL_EPHEMERIS_BASE =
        "https://raw.githubusercontent.com/aloistr/swisseph/master/ephe/";

    let swiss = null;
    let swissModule = null;
    let swissReadyPromise = null;

    async function ensureSwissEphemeris() {
        if (swiss) return swiss;

        if (!swissReadyPromise) {
            swissReadyPromise = (async function () {
                const mod = await import(SWISS_JS_URL);
                const SwissEphemeris =
                    mod.SwissEphemeris || mod.default;

                if (typeof SwissEphemeris !== "function") {
                    throw new Error(
                        "Swiss Ephemeris browser runtime load नहीं हुआ।"
                    );
                }

                const instance = new SwissEphemeris();
                await instance.init();

                /* Lahiri is set inside the Swiss Ephemeris engine itself. */
                if (mod.SiderealMode && mod.SiderealMode.Lahiri !== undefined) {
                    instance.setSiderealMode(mod.SiderealMode.Lahiri);
                } else {
                    throw new Error(
                        "Swiss Ephemeris Lahiri sidereal mode उपलब्ध नहीं है।"
                    );
                }

                /*
                 * Modern births normally fall inside sepl_18/semo_18.
                 * These are fetched from the official Swiss Ephemeris
                 * repository. If a file is unavailable, we fail instead
                 * of silently switching to a less precise ephemeris.
                 */
                if (typeof instance.loadEphemerisFiles !== "function") {
                    throw new Error(
                        "Swiss Ephemeris browser file loader उपलब्ध नहीं है।"
                    );
                }

                /* The actual file is selected lazily per birth year by
                   ensureSwissEphemerisForDate(). */

                swiss = instance;
                swissModule = mod;

                console.log(
                    "[Kundli Engine] Swiss Ephemeris ready:",
                    typeof instance.version === "function"
                        ? instance.version()
                        : "unknown"
                );

                return instance;
            })().catch(function (error) {
                swissReadyPromise = null;
                swiss = null;
                swissModule = null;
                throw error;
            });
        }

        return swissReadyPromise;
    }

    async function ensureSwissEphemerisForDate(date) {
        const instance = await ensureSwissEphemeris();
        const year = date.getUTCFullYear();

        let suffix = null;
        if (year >= 1800 && year <= 2399) suffix = "18";
        else if (year >= 1200 && year <= 1799) suffix = "12";
        else if (year >= 600 && year <= 1199) suffix = "06";
        else if (year >= 0 && year <= 599) suffix = "00";

        if (!suffix) {
            throw new Error(
                "Swiss Ephemeris data range is not bundled for this birth year. " +
                "Current browser build supports official planetary files for 0–2399 CE. " +
                "Extended historical ephemeris files can be added without changing the calculation engine."
            );
        }

        if (!window.__KUNDLI_SWISS_FILES) {
            window.__KUNDLI_SWISS_FILES = {};
        }

        if (!window.__KUNDLI_SWISS_FILES[suffix]) {
            await instance.loadEphemerisFiles([
                {
                    name: `sepl_${suffix}.se1`,
                    url: OFFICIAL_EPHEMERIS_BASE + `sepl_${suffix}.se1`
                },
                {
                    name: `semo_${suffix}.se1`,
                    url: OFFICIAL_EPHEMERIS_BASE + `semo_${suffix}.se1`
                }
            ]);
            window.__KUNDLI_SWISS_FILES[suffix] = true;
        }

        return instance;
    }

    /* =========================================================
       RASHI DATA
    ========================================================= */

    const RASHIS = [
        {
            index: 0,
            id: "aries",
            name: "Mesha",
            hindi: "मेष",
            element: "Fire",
            modality: "Movable"
        },
        {
            index: 1,
            id: "taurus",
            name: "Vrishabha",
            hindi: "वृषभ",
            element: "Earth",
            modality: "Fixed"
        },
        {
            index: 2,
            id: "gemini",
            name: "Mithuna",
            hindi: "मिथुन",
            element: "Air",
            modality: "Dual"
        },
        {
            index: 3,
            id: "cancer",
            name: "Karka",
            hindi: "कर्क",
            element: "Water",
            modality: "Movable"
        },
        {
            index: 4,
            id: "leo",
            name: "Simha",
            hindi: "सिंह",
            element: "Fire",
            modality: "Fixed"
        },
        {
            index: 5,
            id: "virgo",
            name: "Kanya",
            hindi: "कन्या",
            element: "Earth",
            modality: "Dual"
        },
        {
            index: 6,
            id: "libra",
            name: "Tula",
            hindi: "तुला",
            element: "Air",
            modality: "Movable"
        },
        {
            index: 7,
            id: "scorpio",
            name: "Vrishchika",
            hindi: "वृश्चिक",
            element: "Water",
            modality: "Fixed"
        },
        {
            index: 8,
            id: "sagittarius",
            name: "Dhanu",
            hindi: "धनु",
            element: "Fire",
            modality: "Dual"
        },
        {
            index: 9,
            id: "capricorn",
            name: "Makara",
            hindi: "मकर",
            element: "Earth",
            modality: "Movable"
        },
        {
            index: 10,
            id: "aquarius",
            name: "Kumbha",
            hindi: "कुंभ",
            element: "Air",
            modality: "Fixed"
        },
        {
            index: 11,
            id: "pisces",
            name: "Meena",
            hindi: "मीन",
            element: "Water",
            modality: "Dual"
        }
    ];

    /* =========================================================
       NAKSHATRA
    ========================================================= */

    const NAKSHATRAS = [
        ["Ashwini", "अश्विनी", "Ketu", "Deva", "Horse", "Adi"],
        ["Bharani", "भरणी", "Venus", "Manushya", "Elephant", "Madhya"],
        ["Krittika", "कृत्तिका", "Sun", "Rakshasa", "Sheep", "Antya"],
        ["Rohini", "रोहिणी", "Moon", "Manushya", "Serpent", "Adi"],
        ["Mrigashira", "मृगशिरा", "Mars", "Deva", "Serpent", "Madhya"],
        ["Ardra", "आर्द्रा", "Rahu", "Manushya", "Dog", "Antya"],
        ["Punarvasu", "पुनर्वसु", "Jupiter", "Deva", "Cat", "Adi"],
        ["Pushya", "पुष्य", "Saturn", "Deva", "Sheep", "Madhya"],
        ["Ashlesha", "आश्लेषा", "Mercury", "Rakshasa", "Cat", "Antya"],
        ["Magha", "मघा", "Ketu", "Rakshasa", "Rat", "Adi"],
        ["Purva Phalguni", "पूर्व फाल्गुनी", "Venus", "Manushya", "Rat", "Madhya"],
        ["Uttara Phalguni", "उत्तर फाल्गुनी", "Sun", "Manushya", "Cow", "Antya"],
        ["Hasta", "हस्त", "Moon", "Deva", "Buffalo", "Adi"],
        ["Chitra", "चित्रा", "Mars", "Rakshasa", "Tiger", "Madhya"],
        ["Swati", "स्वाती", "Rahu", "Deva", "Buffalo", "Antya"],
        ["Vishakha", "विशाखा", "Jupiter", "Rakshasa", "Tiger", "Adi"],
        ["Anuradha", "अनुराधा", "Saturn", "Deva", "Deer", "Madhya"],
        ["Jyeshtha", "ज्येष्ठा", "Mercury", "Rakshasa", "Deer", "Antya"],
        ["Mula", "मूल", "Ketu", "Rakshasa", "Dog", "Adi"],
        ["Purva Ashadha", "पूर्वाषाढ़ा", "Venus", "Manushya", "Monkey", "Madhya"],
        ["Uttara Ashadha", "उत्तराषाढ़ा", "Sun", "Manushya", "Mongoose", "Antya"],
        ["Shravana", "श्रवण", "Moon", "Deva", "Monkey", "Adi"],
        ["Dhanishtha", "धनिष्ठा", "Mars", "Rakshasa", "Lion", "Madhya"],
        ["Shatabhisha", "शतभिषा", "Rahu", "Rakshasa", "Horse", "Antya"],
        ["Purva Bhadrapada", "पूर्व भाद्रपद", "Jupiter", "Manushya", "Lion", "Adi"],
        ["Uttara Bhadrapada", "उत्तर भाद्रपद", "Saturn", "Manushya", "Cow", "Madhya"],
        ["Revati", "रेवती", "Mercury", "Deva", "Elephant", "Antya"]
    ].map(function (item, index) {
        return {
            index,
            name: item[0],
            hindi: item[1],
            lord: item[2],
            gana: item[3],
            yoni: item[4],
            nadi: item[5]
        };
    });

    /* =========================================================
       VIMSHOTTARI DASHA
    ========================================================= */

    const DASHA_ORDER = [
        "Ketu",
        "Venus",
        "Sun",
        "Moon",
        "Mars",
        "Rahu",
        "Jupiter",
        "Saturn",
        "Mercury"
    ];

    const DASHA_YEARS = {
        Ketu: 7,
        Venus: 20,
        Sun: 6,
        Moon: 10,
        Mars: 7,
        Rahu: 18,
        Jupiter: 16,
        Saturn: 19,
        Mercury: 17
    };

    /* =========================================================
       PLANETS
    ========================================================= */

    const PLANETS = [
        {
            id: "Sun",
            hindi: "सूर्य",
            body: "Sun"
        },
        {
            id: "Moon",
            hindi: "चंद्र",
            body: "Moon"
        },
        {
            id: "Mars",
            hindi: "मंगल",
            body: "Mars"
        },
        {
            id: "Mercury",
            hindi: "बुध",
            body: "Mercury"
        },
        {
            id: "Jupiter",
            hindi: "गुरु",
            body: "Jupiter"
        },
        {
            id: "Venus",
            hindi: "शुक्र",
            body: "Venus"
        },
        {
            id: "Saturn",
            hindi: "शनि",
            body: "Saturn"
        }
    ];

    /* =========================================================
       HELPERS
    ========================================================= */

    function normalize360(value) {
        let result = Number(value) % 360;

        if (result < 0) {
            result += 360;
        }

        return result;
    }

    function signedAngle(a, b) {
        let diff = normalize360(a - b);

        if (diff > 180) {
            diff -= 360;
        }

        return diff;
    }

    function formatDegree(degree) {
        const d = normalize360(degree);

        let deg = Math.floor(d);
        let min = Math.round((d - deg) * 60);

        if (min === 60) {
            deg++;
            min = 0;
        }

        return `${deg}° ${String(min).padStart(2, "0")}′`;
    }

    function getRashi(longitude) {
        const index = Math.floor(
            normalize360(longitude) / 30
        );

        return {
            ...RASHIS[index],
            index
        };
    }

    function getDegreeInRashi(longitude) {
        return normalize360(longitude) % 30;
    }

    /* =========================================================
       LAHIRI AYANAMSHA
    ========================================================= */

    function calculateLahiriAyanamsha(date) {
        if (!swiss) {
            throw new Error(
                "Swiss Ephemeris अभी initialize नहीं हुआ है।"
            );
        }

        const jd = swiss.dateToJulianDay(date);
        return Number(
            swiss.getAyanamsa(jd)
        );
    }

    /* =========================================================
       NAKSHATRA
    ========================================================= */

    function getNakshatra(longitude) {
        const span = 360 / 27;
        const padaSpan = span / 4;

        const value =
            normalize360(longitude);

        const index =
            Math.min(
                26,
                Math.floor(value / span)
            );

        const inside =
            value - index * span;

        const pada =
            Math.min(
                4,
                Math.floor(
                    inside / padaSpan
                ) + 1
            );

        const nak =
            NAKSHATRAS[index];

        return {
            id: String(nak.name || "").toLowerCase().replace(/\s+/g, "-"),
            index,
            name: nak.name,
            hindi: nak.hindi,
            lord: nak.lord,
            gana: nak.gana,
            yoni: nak.yoni,
            nadi: nak.nadi,
            pada,
            degree: inside
        };
    }

    /* =========================================================
       NAVAMSA
    ========================================================= */

    function getNavamsa(longitude) {
        const rashi =
            getRashi(longitude);

        const part =
            Math.min(
                8,
                Math.floor(
                    getDegreeInRashi(longitude) /
                    (30 / 9)
                )
            );

        let start;

        if (
            rashi.modality ===
            "Movable"
        ) {
            start = rashi.index;
        } else if (
            rashi.modality ===
            "Fixed"
        ) {
            start =
                (rashi.index + 8) % 12;
        } else {
            start =
                (rashi.index + 4) % 12;
        }

        const navamsaIndex =
            (start + part) % 12;

        return {
            index: navamsaIndex,
            sign: {
                ...RASHIS[navamsaIndex]
            },
            pada: part + 1
        };
    }

    /* =========================================================
       MEAN RAHU
    ========================================================= */

    /* =========================================================
       GEOCENTRIC PLANET POSITIONS
    ========================================================= */

    function calculatePlanetLongitudes(date) {
        if (!swiss || !swissModule) {
            throw new Error(
                "Swiss Ephemeris initialize नहीं हुआ है।"
            );
        }

        const flags =
            swissModule.CalculationFlag.SwissEphemeris |
            swissModule.CalculationFlag.Sidereal |
            swissModule.CalculationFlag.Speed;

        const bodyMap = {
            Sun: swissModule.Planet.Sun,
            Moon: swissModule.Planet.Moon,
            Mercury: swissModule.Planet.Mercury,
            Venus: swissModule.Planet.Venus,
            Mars: swissModule.Planet.Mars,
            Jupiter: swissModule.Planet.Jupiter,
            Saturn: swissModule.Planet.Saturn
        };

        const jd = swiss.dateToJulianDay(date);
        const tropical = {};
        const sidereal = {};
        const motion = {};
        const ephemeris = {};

        PLANETS.forEach(function (planet) {
            const body = bodyMap[planet.id];
            const position = swiss.calculatePosition(
                jd,
                body,
                flags
            );

            if (!position || !Number.isFinite(position.longitude)) {
                throw new Error(
                    `${planet.id} की Swiss Ephemeris position calculate नहीं हुई।`
                );
            }

            /* Swiss Ephemeris returns sidereal longitude because
               CalculationFlag.Sidereal + Lahiri are active. */
            sidereal[planet.id] = normalize360(position.longitude);
            motion[planet.id] = Number(position.longitudeSpeed || 0);
            ephemeris[planet.id] = position.flags;

            /* Tropical longitude is retained for transparency.
               Swiss Lahiri ayanamsha is applied by the engine itself. */
            const ayan = calculateLahiriAyanamsha(date);
            tropical[planet.id] = normalize360(
                position.longitude + ayan
            );
        });

        const nodePosition = swiss.calculatePosition(
            jd,
            swissModule.LunarPoint.MeanNode,
            flags
        );

        if (!nodePosition || !Number.isFinite(nodePosition.longitude)) {
            throw new Error(
                "Swiss Ephemeris Mean Rahu position calculate नहीं हुई।"
            );
        }

        sidereal.Rahu = normalize360(nodePosition.longitude);
        sidereal.Ketu = normalize360(sidereal.Rahu + 180);
        motion.Rahu = Number(nodePosition.longitudeSpeed || 0);
        motion.Ketu = motion.Rahu;
        ephemeris.Rahu = nodePosition.flags;
        ephemeris.Ketu = nodePosition.flags;

        const ayan = calculateLahiriAyanamsha(date);
        tropical.Rahu = normalize360(sidereal.Rahu + ayan);
        tropical.Ketu = normalize360(tropical.Rahu + 180);

        return {
            tropical,
            sidereal,
            motion,
            ephemeris
        };
    }

    /* =========================================================
       RETROGRADE / DAILY MOTION
    ========================================================= */

    function calculateMotion(motion) {
        const value = Number(motion);
        return {
            retrograde: Number.isFinite(value) ? value < 0 : false,
            motion: Number.isFinite(value) ? value : 0
        };
    }

    /* =========================================================
       ASCENDANT
    ========================================================= */

    function calculateAscendant(
        date,
        latitude,
        longitude
    ) {
        if (!swiss) {
            throw new Error(
                "Swiss Ephemeris initialize नहीं हुआ है।"
            );
        }

        const jd = swiss.dateToJulianDay(date);
        const houses = swiss.calculateHouses(
            jd,
            latitude,
            longitude,
            swissModule.HouseSystem.WholeSign
        );

        if (!houses || !Number.isFinite(houses.ascendant)) {
            throw new Error(
                "Swiss Ephemeris Ascendant calculate नहीं हुआ।"
            );
        }

        const ayanamsa = calculateLahiriAyanamsha(date);
        const tropicalAscendant = normalize360(houses.ascendant);
        const siderealAscendant = normalize360(
            tropicalAscendant - ayanamsa
        );
        const rashi = getRashi(siderealAscendant);

        return {
            tropicalLongitude: tropicalAscendant,
            siderealLongitude: siderealAscendant,
            rashi,
            rashiLord: SIGN_LORDS[rashi.index],
            degree: getDegreeInRashi(siderealAscendant),
            degreeFormatted: formatDegree(
                getDegreeInRashi(siderealAscendant)
            ),
            localSiderealTime: Number(houses.armc || 0),
            ayanamsha,
            midheavenTropical: Number(houses.mc || 0),
            vertexTropical: Number(houses.vertex || 0),
            houseSystem: "Whole Sign"
        };
    }

    /* =========================================================
       CANONICAL DERIVED PLANETARY FACTORS
    ========================================================= */
    const SIGN_LORDS = ["Mars","Venus","Mercury","Moon","Sun","Mercury","Venus","Mars","Jupiter","Saturn","Saturn","Jupiter"];
    const EXALTATION = {Sun:[0,10],Moon:[1,3],Mars:[9,28],Mercury:[5,15],Jupiter:[3,5],Venus:[11,27],Saturn:[6,20]};
    const DEBILITATION = {Sun:[6,10],Moon:[7,3],Mars:[3,28],Mercury:[11,15],Jupiter:[9,5],Venus:[5,27],Saturn:[0,20]};
    const MOOLATRIKONA = {Sun:[4,0,20],Moon:[1,4,30],Mars:[0,0,12],Mercury:[5,16,20],Jupiter:[8,0,10],Venus:[6,0,15],Saturn:[10,0,20]};
    const COMBUSTION_LIMITS = {Mars:17,Mercury:14,Jupiter:11,Venus:10,Saturn:15};
    const SPECIAL_ASPECTS = {Mars:[4,7,8],Jupiter:[5,7,9],Saturn:[3,7,10]};
    function angularDistance(a,b){const d=Math.abs(normalize360(a)-normalize360(b));return Math.min(d,360-d);}
    function dignityOf(id,rashi,degree){if(!rashi)return {key:"unknown",label:"डेटा उपलब्ध नहीं"};const s=Number(rashi.index),d=Number(degree);if(EXALTATION[id]?.[0]===s)return {key:"exalted",label:"उच्च / Exalted"};if(DEBILITATION[id]?.[0]===s)return {key:"debilitated",label:"नीच / Debilitated"};const m=MOOLATRIKONA[id];if(m&&s===m[0]&&d>=m[1]&&d<m[2])return {key:"moolatrikona",label:"मूलत्रिकोण / Mooltrikona"};if(SIGN_LORDS[s]===id)return {key:"own",label:"स्वक्षेत्री / Own Sign"};return {key:"neutral",label:"सामान्य / Neutral"};}
    function enrichPlanetFactors(planets,sunLongitude){Object.keys(planets).forEach(id=>{const p=planets[id];p.rashiLord=p.rashi?SIGN_LORDS[p.rashi.index]:null;p.dignity=dignityOf(id,p.rashi,p.degree);if(id==="Sun"||id==="Rahu"||id==="Ketu"){p.combust=false;p.combustDistance=null;}else if(Number.isFinite(Number(sunLongitude))){p.combustDistance=angularDistance(sunLongitude,p.longitude);p.combust=p.combustDistance<=(COMBUSTION_LIMITS[id]||0);}else{p.combust=false;p.combustDistance=null;}p.aspectHouses=(SPECIAL_ASPECTS[id]||[7]).slice();});Object.keys(planets).forEach(id=>{const p=planets[id],lord=p.rashiLord,d=lord&&planets[lord];p.dispositor=d?{id:lord,rashi:d.rashi,house:d.house||null}:null;});}

    /* =========================================================
       PLANET TABLE
    ========================================================= */

    function buildPlanetTable(
        date,
        siderealPositions,
        motionPositions,
        ephemerisFlags
    ) {
        const planets = {};

        PLANETS.forEach(function (planet) {
            const longitude =
                siderealPositions[
                    planet.id
                ];

            const rashi =
                getRashi(longitude);

            const nakshatra =
                getNakshatra(
                    longitude
                );

            const navamsa =
                getNavamsa(
                    longitude
                );

            const motion =
                calculateMotion(
                    motionPositions[planet.id]
                );

            planets[planet.id] = {
                id:
                    planet.id,

                name:
                    planet.id,

                hindi:
                    planet.hindi,

                longitude:
                    Number(
                        longitude.toFixed(6)
                    ),

                degree:
                    Number(
                        getDegreeInRashi(
                            longitude
                        ).toFixed(6)
                    ),

                degreeFormatted:
                    formatDegree(
                        getDegreeInRashi(
                            longitude
                        )
                    ),

                rashi,

                nakshatra,

                navamsa,

                retrograde:
                    Boolean(
                        motion.retrograde
                    ),

                dailyMotion:
                    Number(
                        motion.motion.toFixed(6)
                    ),

                ephemerisFlags:
                    ephemerisFlags[planet.id] ?? null
            };
        });

        /* =====================================================
           RAHU / KETU
        ===================================================== */

        ["Rahu", "Ketu"].forEach(
            function (node) {
                const longitude =
                    siderealPositions[
                        node
                    ];

                planets[node] = {
                    id:
                        node,

                    name:
                        node,

                    hindi:
                        node === "Rahu"
                            ? "राहु"
                            : "केतु",

                    longitude:
                        Number(
                            longitude.toFixed(6)
                        ),

                    degree:
                        Number(
                            getDegreeInRashi(
                                longitude
                            ).toFixed(6)
                        ),

                    degreeFormatted:
                        formatDegree(
                            getDegreeInRashi(
                                longitude
                            )
                        ),

                    rashi:
                        getRashi(
                            longitude
                        ),

                    nakshatra:
                        getNakshatra(
                            longitude
                        ),

                    navamsa:
                        getNavamsa(
                            longitude
                        ),

                    /*
                     * Rahu/Ketu are conventionally
                     * treated as retrograde in Jyotish.
                     */
                    retrograde:
                        calculateMotion(
                            motionPositions[node]
                        ).retrograde,

                    dailyMotion:
                        Number(
                            motionPositions[node] || 0
                        ),

                    ephemerisFlags:
                        ephemerisFlags[node] ?? null
                };
            }
        );

        return planets;
    }

    /* =========================================================
       WHOLE SIGN HOUSES
    ========================================================= */

    function assignHouses(
        ascendant,
        planets
    ) {
        const ascendantSign =
            ascendant.rashi.index;

        const houses = [];

        for (
            let house = 1;
            house <= 12;
            house++
        ) {
            const signIndex =
                (
                    ascendantSign +
                    house -
                    1
                ) % 12;

            houses.push({
                house,
                rashi: { ...RASHIS[signIndex] },
                lord: SIGN_LORDS[signIndex]
            });
        }

        Object.keys(planets)
            .forEach(function (id) {
                const planet =
                    planets[id];

                const house =
                    (
                        planet.rashi.index -
                        ascendantSign +
                        12
                    ) % 12 + 1;

                planet.house =
                    house;
            });

        return houses;
    }

    /* =========================================================
       D9 NAVAMSA
    ========================================================= */

    function buildNavamsa(
        ascendant,
        planets
    ) {
        const result = {
            lagna: {
                ...getNavamsa(
                    ascendant.siderealLongitude
                )
            },

            planets: {}
        };

        Object.keys(planets)
            .forEach(function (id) {
                const d9 = getNavamsa(planets[id].longitude);
                const d9Sign = d9.sign.index;
                result.planets[id] = {
                    id,
                    longitude: planets[id].longitude,
                    navamsa: d9,
                    house: ((d9Sign - result.lagna.sign.index + 12) % 12) + 1,
                    rashiLord: SIGN_LORDS[d9Sign]
                };
            });

        return result;
    }

    /* =========================================================
       VIMSHOTTARI DASHA
    ========================================================= */

    function calculateAntardasha(
        mahaLord,
        mahaStart,
        mahaYears
    ) {
        const startIndex =
            DASHA_ORDER.indexOf(
                mahaLord
            );

        const totalYears =
            120;

        let cursor =
            new Date(
                mahaStart.getTime()
            );

        const result = [];

        for (
            let i = 0;
            i < 9;
            i++
        ) {
            const lord =
                DASHA_ORDER[
                    (
                        startIndex +
                        i
                    ) % 9
                ];

            const years =
                mahaYears *
                (
                    DASHA_YEARS[
                        lord
                    ] /
                    totalYears
                );

            const start =
                new Date(
                    cursor.getTime()
                );

            const end =
                new Date(
                    cursor.getTime() +
                    years *
                    365.2425 *
                    86400000
                );

            result.push({
                lord,

                years,

                start:
                    start.toISOString(),

                end:
                    end.toISOString()
            });

            cursor =
                end;
        }

        return result;
    }

    function calculateVimshottari(
        moonLongitude,
        birthDate
    ) {
        const nak =
            getNakshatra(
                moonLongitude
            );

        const nakshatraSpan =
            360 / 27;

        const elapsed =
            nak.degree /
            nakshatraSpan;

        const firstLord =
            nak.lord;

        const firstIndex =
            DASHA_ORDER.indexOf(
                firstLord
            );

        const remainingYears =
            DASHA_YEARS[
                firstLord
            ] *
            (
                1 -
                elapsed
            );

        let cursor =
            new Date(
                birthDate.getTime()
            );

        const mahadasha = [];

        for (
            let i = 0;
            i < 9;
            i++
        ) {
            const lord =
                DASHA_ORDER[
                    (
                        firstIndex +
                        i
                    ) % 9
                ];

            const years =
                i === 0
                    ? remainingYears
                    : DASHA_YEARS[
                        lord
                    ];

            const start =
                new Date(
                    cursor.getTime()
                );

            const end =
                new Date(
                    cursor.getTime() +
                    years *
                    365.2425 *
                    86400000
                );

            mahadasha.push({
                lord,

                years,

                start:
                    start.toISOString(),

                end:
                    end.toISOString(),

                antardasha:
                    calculateAntardasha(
                        lord,
                        start,
                        years
                    )
            });

            cursor =
                end;
        }

        return {
            system:
                "Vimshottari",

            birthNakshatra:
                nak,

            mahadasha
        };
    }

    /* =========================================================
       MANGLIK
    ========================================================= */

    function houseFromSign(
        planetSign,
        referenceSign
    ) {
        return (
            (
                planetSign -
                referenceSign +
                12
            ) % 12
        ) + 1;
    }

    function calculateManglik(
        planets,
        ascendant
    ) {
        const mars =
            planets.Mars;

        const moon =
            planets.Moon;

        const venus =
            planets.Venus;

        const fromLagna =
            houseFromSign(
                mars.rashi.index,
                ascendant.rashi.index
            );

        const fromMoon =
            houseFromSign(
                mars.rashi.index,
                moon.rashi.index
            );

        const fromVenus =
            houseFromSign(
                mars.rashi.index,
                venus.rashi.index
            );

        const affected = [
            fromLagna,
            fromMoon,
            fromVenus
        ].filter(
            function (house) {
                return [
                    1,
                    2,
                    4,
                    7,
                    8,
                    12
                ].includes(house);
            }
        );

        let assessment =
            "Not indicated";

        if (
            affected.length >= 2
        ) {
            assessment =
                "Strong traditional indication";
        } else if (
            affected.length === 1
        ) {
            assessment =
                "Single traditional indication";
        }

        return {
            marsHouseFromLagna:
                fromLagna,

            marsHouseFromMoon:
                fromMoon,

            marsHouseFromVenus:
                fromVenus,

            affectedReferences:
                affected.length,

            isManglik:
                affected.length > 0,

            assessment,

            note:
                "Manglik assessment is a traditional Jyotish interpretation."
        };
    }

    /* =========================================================
       VEDIC ASPECTS
    ========================================================= */

    function getAspectHouses(
        planet
    ) {
        if (
            planet === "Mars"
        ) {
            return [
                4,
                7,
                8
            ];
        }

        if (
            planet === "Jupiter"
        ) {
            return [
                5,
                7,
                9
            ];
        }

        if (
            planet === "Saturn"
        ) {
            return [
                3,
                7,
                10
            ];
        }

        return [
            7
        ];
    }

    function calculateAspects(
        planets
    ) {
        const aspects = [];

        Object.keys(planets)
            .forEach(
                function (id) {
                    const planet =
                        planets[id];

                    if (
                        !planet.house
                    ) {
                        return;
                    }

                    getAspectHouses(id)
                        .forEach(
                            function (offset) {
                                const targetHouse =
                                    (
                                        planet.house -
                                        1 +
                                        offset -
                                        1
                                    ) % 12 + 1;

                                aspects.push({
                                    source:
                                        id,

                                    sourceHouse:
                                        planet.house,

                                    aspect:
                                        offset,

                                    targetHouse
                                });
                            }
                        );
                }
            );

        return aspects;
    }

    /* =========================================================
       MAIN CALCULATION
    ========================================================= */

    async function calculate(input) {
        if (!input) {
            throw new Error(
                "Kundli input missing."
            );
        }

        if (!input.utcDate) {
            throw new Error(
                "utcDate missing."
            );
        }

        const birthDate =
            input.utcDate instanceof Date
                ? new Date(
                    input.utcDate.getTime()
                )
                : new Date(
                    input.utcDate
                );

        if (
            Number.isNaN(
                birthDate.getTime()
            )
        ) {
            throw new Error(
                "Invalid UTC birth date."
            );
        }

        await ensureSwissEphemerisForDate(birthDate);

        if (
            !Number.isFinite(
                Number(
                    input.latitude
                )
            ) ||
            !Number.isFinite(
                Number(
                    input.longitude
                )
            )
        ) {
            throw new Error(
                "Valid latitude and longitude are required."
            );
        }

        if (
            Number(input.latitude) <
                -90 ||
            Number(input.latitude) >
                90
        ) {
            throw new Error(
                "Latitude must be between -90 and 90."
            );
        }

        if (
            Number(input.longitude) <
                -180 ||
            Number(input.longitude) >
                180
        ) {
            throw new Error(
                "Longitude must be between -180 and 180."
            );
        }

        if (
            birthDate.getTime() >
            Date.now()
        ) {
            throw new Error(
                "Birth date cannot be in the future."
            );
        }

        /* =====================================================
           PLANET CALCULATION
        ===================================================== */

        const positions =
            calculatePlanetLongitudes(
                birthDate
            );

        /* =====================================================
           LAGNA
        ===================================================== */

        const ascendant =
            calculateAscendant(
                birthDate,

                Number(
                    input.latitude
                ),

                Number(
                    input.longitude
                )
            );

        /* =====================================================
           PLANET TABLE
        ===================================================== */

        const planets =
            buildPlanetTable(
                birthDate,
                positions.sidereal,
                positions.motion,
                positions.ephemeris
            );

        /* =====================================================
           HOUSES
        ===================================================== */

        const houses =
            assignHouses(
                ascendant,
                planets
            );

        enrichPlanetFactors(
            planets,
            planets.Sun ? planets.Sun.longitude : null
        );

        /* =====================================================
           D9
        ===================================================== */

        const navamsa =
            buildNavamsa(
                ascendant,
                planets
            );

        /* =====================================================
           DASHA
        ===================================================== */

        const dasha =
            calculateVimshottari(
                planets.Moon.longitude,
                birthDate
            );

        /* =====================================================
           MANGLIK
        ===================================================== */

        const manglik =
            calculateManglik(
                planets,
                ascendant
            );

        /* =====================================================
           ASPECTS
        ===================================================== */

        const aspects =
            calculateAspects(
                planets
            );

        /* =====================================================
           FINAL RESULT
        ===================================================== */

        return {
            version:
                "3.0.0",

            engine: {
                provider:
                    "Swiss Ephemeris",

                providerVersion:
                    typeof swiss.version === "function"
                        ? swiss.version()
                        : "unknown",

                ephemerisSource:
                    "Astrodienst Swiss Ephemeris official ephemeris files",

                ayanamsha:
                    "Lahiri (Swiss Ephemeris sidereal mode)",

                houseSystem:
                    "Whole Sign",

                calculation:
                    "Geocentric sidereal planetary positions using Swiss Ephemeris"
            },

            input: {
                name:
                    input.name || "",

                gender:
                    input.gender || "",

                birthDate:
                    input.birthDate || "",

                birthTime:
                    input.birthTime || "",

                birthPlace:
                    input.birthPlace ||
                    input.place ||
                    "",

                latitude:
                    Number(
                        input.latitude
                    ),

                longitude:
                    Number(
                        input.longitude
                    ),

                timezone:
                    input.timezone || "",

                utcDate:
                    birthDate.toISOString()
            },

            ayanamsha: {
                name:
                    "Lahiri",

                degrees:
                    calculateLahiriAyanamsha(
                        birthDate
                    )
            },

            ephemeris: {
                provider: "Swiss Ephemeris",
                source: "Astrodienst official Swiss Ephemeris repository",
                files: [
                    `sepl_${birthDate.getUTCFullYear() >= 1800 ? "18" : birthDate.getUTCFullYear() >= 1200 ? "12" : birthDate.getUTCFullYear() >= 600 ? "06" : "00"}.se1`,
                    `semo_${birthDate.getUTCFullYear() >= 1800 ? "18" : birthDate.getUTCFullYear() >= 1200 ? "12" : birthDate.getUTCFullYear() >= 600 ? "06" : "00"}.se1`
                ],
                calculation: "Swiss Ephemeris + Lahiri sidereal mode + mean lunar node"
            },

            lagna:
                ascendant,

            planets,

            houses,

            navamsa,

            moonNakshatra:
                planets.Moon.nakshatra,

            dasha,

            manglik,

            aspects,

            calculatedAt:
                new Date().toISOString()
        };
    }

    /* =========================================================
       BACKWARD-COMPATIBLE DERIVED DATA ENRICHMENT
       ---------------------------------------------------------
       Rehydrates older localStorage records without inventing
       any new astronomical position. All values are derived from
       the stored longitude/rashi/house data.
    ========================================================= */

    function enrichKundli(kundli) {
        if (!kundli || typeof kundli !== "object") return kundli;
        const planets = kundli.planets || {};
        if (kundli.houses && Array.isArray(kundli.houses)) {
            kundli.houses.forEach(function(h){
                if (h && h.rashi && h.lord == null) h.lord = SIGN_LORDS[h.rashi.index];
            });
        }
        if (kundli.lagna && kundli.lagna.rashi && kundli.lagna.rashiLord == null) {
            kundli.lagna.rashiLord = SIGN_LORDS[kundli.lagna.rashi.index];
        }
        enrichPlanetFactors(planets, planets.Sun ? planets.Sun.longitude : null);
        Object.keys(planets).forEach(function(id){
            const p = planets[id];
            const longitude = Number(p.longitude);
            if (Number.isFinite(longitude)) {
                /* Rebuild all deterministic chart metadata from the
                   stored sidereal longitude so older localStorage
                   records also receive the complete data model. */
                p.rashi = getRashi(longitude);
                p.nakshatra = getNakshatra(longitude);
                p.navamsa = getNavamsa(longitude);
                p.degree = Number(getDegreeInRashi(longitude).toFixed(6));
                p.degreeFormatted = formatDegree(getDegreeInRashi(longitude));
            }
        });
        if (kundli.lagna && !kundli.navamsa) kundli.navamsa = buildNavamsa(kundli.lagna, planets);
        else if (kundli.lagna && kundli.navamsa) {
            if (!kundli.navamsa.lagna) kundli.navamsa.lagna = getNavamsa(kundli.lagna.siderealLongitude);
            Object.keys(planets).forEach(function(id){
                if (!kundli.navamsa.planets) kundli.navamsa.planets = {};
                const d9 = planets[id].navamsa;
                if (d9 && !kundli.navamsa.planets[id]) kundli.navamsa.planets[id] = {id,longitude:planets[id].longitude,navamsa:d9};
            });
        }
        if (kundli.navamsa && kundli.navamsa.lagna) {
            const lagnaIndex = kundli.navamsa.lagna.sign.index;
            Object.keys(kundli.navamsa.planets || {}).forEach(function(id){
                const d = kundli.navamsa.planets[id];
                const sign = d && d.navamsa && d.navamsa.sign;
                if (sign) { d.house = ((sign.index - lagnaIndex + 12) % 12) + 1; d.rashiLord = SIGN_LORDS[sign.index]; }
            });
        }
        kundli.moonNakshatra = planets.Moon ? planets.Moon.nakshatra : kundli.moonNakshatra;
        return kundli;
    }

    /* =========================================================
       PUBLIC API
    ========================================================= */

    window.KundliEngine = {
        version:
            "3.0.0",

        calculate,

        ready: ensureSwissEphemeris,

        utils: {
            normalize360,

            getRashi,

            getNakshatra,

            getNavamsa,

            calculateLahiriAyanamsha,

            formatDegree,

            enrichKundli,

            getPlanetDignity: dignityOf,

            getSignLord: function(index) {
                return SIGN_LORDS[Number(index)] || null;
            }
        }
    };

})(window);